pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    Python:
      python.version: '3.7'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda create --yes --quiet --name jupyterlab-debugger
  displayName: Create a new conda environment

- bash: |
    source activate jupyterlab-debugger
    conda install --yes --quiet -c conda-forge nodejs xeus-python ptvsd python=$PYTHON_VERSION
    python -m pip install -U --pre jupyterlab
  displayName: Install dependencies

- bash: |
    source activate jupyterlab-debugger
    mkdir ~/.jupyter
    jlpm
    jlpm run build
  displayName: Build jupyterlab-debugger

- bash: |
    source activate jupyterlab-debugger
    export JUPYTER_PATH=${CONDA_PREFIX}/share/jupyter
    export XEUS_LOG=1
    jlpm run test
  displayName: Run the tests
