# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python:
      python.version: '3.7'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda create --yes --quiet --name jupyterlab-debugger -c conda-forge jupyterlab nodejs xeus-python ptvsd
  displayName: Create Anaconda environment

- bash: |
    source activate jupyterlab-debugger
    python -m pip install -U --pre jupyterlab
  displayName: Install JupyterLab 1.1a

- bash: |
    source activate jupyterlab-debugger
    jlpm
    jlpm run build
    jupyter labextension link .
  displayName: Build jupyterlab-debugger

- bash: |
    source activate jupyterlab-debugger
    jlpm run test
  displayName: Run the tests
